version: '3'

services:
  web:
    build: .
    ports:
    - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://papi:OTkwLNke1sHFBcxp@cluster0.aw1sncn.mongodb.net/ispent?retryWrites=true&w=majority
      - PEM_PASSPHRASE=7778
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=ispent
      - MONGO_INITDB_ROOT_USERNAME=papi
      - MONGO_INITDB_ROOT_PASSWORD=OTkwLNke1sHFBcxp
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongod.conf:/etc/mongo/mongod.conf

volumes:
  app:
  mongo_data: